[[redirects]]
  from = "/community/teams/nixpkgs-architecture"
  to = "https://github.com/nixpkgs-architecture"
  status = 302
  force = true

[[redirects]]
  from = "/news.xml"
  to = "/blog/announcements.xml"
  status = 302
  force = true

[[redirects]]
  from = "/news-rss.xml"
  to = "/blog/announcements-rss.xml"
  status = 302
  force = true

[[redirects]]
  from = "/community.html"
  to = "/community/index.html"
  status = 302
  force = true

[[redirects]]
  from = "/teams/discourse.html"
  to = "/community/teams/moderation.html"
  status = 302
  force = true

[[redirects]]
  from = "/community/teams/discourse.html"
  to = "/community/teams/moderation.html"
  status = 302
  force = true

[[redirects]]
  from = "/teams/infrastructure.html"
  to = "/community/teams/infrastructure.html"
  status = 302
  force = true

[[redirects]]
  from = "/teams/marketing.html"
  to = "/community/teams/marketing.html"
  status = 302
  force = true

[[redirects]]
  from = "/teams/nixcon.html"
  to = "/community/teams/nixcon.html"
  status = 302
  force = true

[[redirects]]
  from = "/teams/nixos_release.html"
  to = "/community/teams/nixos-release.html"
  status = 302
  force = true

[[redirects]]
  from = "/teams/rfc-steering-committee.html"
  to = "/community/teams/rfc-steering-committee.html"
  status = 302
  force = true

[[redirects]]
  from = "/teams/security.html"
  to = "/community/teams/security.html"
  status = 302
  force = true

[[redirects]]
  from = "/commercial-support.html"
  to = "/community/commercial-support.html"
  status = 302
  force = true

[[redirects]]
  from = "/news.html"
  to = "/blog/announcements.html"
  status = 302
  force = true

[[redirects]]
  from = "/archive.html"
  to = "/blog/announcements.html"
  status = 302
  force = true

[[redirects]]
  from = "/governance.html"
  to = "/community/index.html"
  status = 302
  force = true

[[redirects]]
  from = "/features.html"
  to = "/explore.html"
  status = 302
  force = true

[[redirects]]
  from = "/calendar.ics"
  to = "https://calendar.google.com/calendar/ical/b9o52fobqjak8oq8lfkhg3t0qg%40group.calendar.google.com/public/basic.ics"
  status = 200
  force = true

[[redirects]]
  from = "/manual"
  to = "/learn.html"
  status = 302
  force = true

[[redirects]]
  from = "/manual/nix/*"
  to = "https://nix.dev/manual/nix/stable/:splat"
  status = 302
  force = true

[[redirects]]
  from = "/manual/nixpkgs"
  to = "/manual/nixpkgs/stable"
  status = 302
  force = true

[[redirects]]
  from = "/manual/nixos"
  to = "/manual/nixos/stable"
  status = 302
  force = true

[[redirects]]
  from = "/nixos/nix-pills/*"
  to = "/guides/nix-pills/:splat"
  status = 302
  force = true

[[redirects]]
  from = "/guides/nix-language.html"
  to = "https://nix.dev/tutorials/first-steps/nix-language"
  status = 301
  force = true

[[redirects]]
  from = "/guides/ad-hoc-developer-environments.html"
  to = "https://nix.dev/tutorials/first-steps/ad-hoc-developer-environments"
  status = 301
  force = true

[[redirects]]
  from = "/guides/towards-reproducibility-pinning-nixpkgs.html"
  to = "https://nix.dev/tutorials/first-steps/towards-reproducibility-pinning-nixpkgs"
  status = 301
  force = true

[[redirects]]
  from = "/guides/declarative-and-reproducible-developer-environments.html"
  to = "https://nix.dev/tutorials/first-steps/declarative-and-reproducible-developer-environments"
  status = 301
  force = true

[[redirects]]
  from = "/guides/continuous-integration-github-actions.html"
  to = "https://nix.dev/tutorials/nixos/build-and-deploy/continuous-integration-github-actions"
  status = 301
  force = true

[[redirects]]
  from = "/guides/dev-environment.html"
  to = "https://nix.dev/tutorials/first-steps/dev-environment"
  status = 301
  force = true

[[redirects]]
  from = "/guides/building-and-running-docker-images.html"
  to = "https://nix.dev/tutorials/nixos/build-and-deploy/building-and-running-docker-images"
  status = 301
  force = true

[[redirects]]
  from = "/guides/building-bootable-iso-image.html"
  to = "https://nix.dev/tutorials/nixos/build-and-deploy/building-bootable-iso-image"
  status = 301
  force = true

[[redirects]]
  from = "/guides/deploying-nixos-using-terraform.html"
  to = "https://nix.dev/tutorials/nixos/build-and-deploy/deploying-nixos-using-terraform"
  status = 301
  force = true

[[redirects]]
  from = "/guides/installing-nixos-on-a-raspberry-pi.html"
  to = "https://nix.dev/tutorials/nixos/build-and-deploy/installing-nixos-on-a-raspberry-pi"
  status = 301
  force = true

[[redirects]]
  from = "/guides/integration-testing-using-virtual-machines.html"
  to = "https://nix.dev/tutorials/nixos/build-and-deploy/integration-testing-using-virtual-machines"
  status = 301
  force = true

[[redirects]]
  from = "/guides/cross-compilation.html"
  to = "https://nix.dev/tutorials/nixos/build-and-deploy/cross-compilation"
  status = 301
  force = true

[[redirects]]
  from = "/guides/contributing.html"
  to = "https://nix.dev/contributing/how-to-contribute"
  status = 301
  force = true

[[redirects]]
  from = "/nix/manual/*"
  to = "/manual/nix/stable/:splat"
  status = 302
  force = true

[[redirects]]
  from = "/nixpkgs/manual/*"
  to = "/manual/nixpkgs/stable/:splat"
  status = 302
  force = true

[[redirects]]
  from = "/nixos/manual/*"
  to = "/manual/nixos/stable/:splat"
  status = 302
  force = true

[[redirects]]
  from = "/nixos/packages.html"
  to = "https://search.nixos.org/packages"
  status = 302
  force = true

[[redirects]]
  from = "/nixos/options.html"
  to = "https://search.nixos.org/options"
  status = 302
  force = true

[[redirects]]
  from = "/nixos/wiki.html"
  to = "https://wiki.nixos.org"
  status = 302
  force = true

[[redirects]]
  from = "/nix"
  to = "/"
  status = 302
  force = true

[[redirects]]
  from = "/nix/index.html"
  to = "/"
  status = 302
  force = true

[[redirects]]
  from = "/nix/about.html"
  to = "/explore.html"
  status = 302
  force = true

[[redirects]]
  from = "/nix/learn.html"
  to = "/learn.html"
  status = 302
  force = true

[[redirects]]
  from = "/nix/download"
  to = "/download"
  status = 302
  force = true

[[redirects]]
  from = "/nixpkgs"
  to = "/"
  status = 302
  force = true

[[redirects]]
  from = "/nixpkgs/index.html"
  to = "/"
  status = 302
  force = true

[[redirects]]
  from = "/nixpkgs/download"
  to = "/download"
  status = 302
  force = true

[[redirects]]
  from = "/nixpkgs/packages-nixos-19.09.json.gz"
  to = "https://channels.nixos.org/nixos-19.09/packages.json.br"
  status = 302
  force = true

[[redirects]]
  from = "/nixpkgs/packages-nixos-unstable.json.gz"
  to = "https://channels.nixos.org/nixos-unstable/packages.json.br"
  status = 302
  force = true

[[redirects]]
  from = "/nixos"
  to = "/"
  status = 302
  force = true

[[redirects]]
  from = "/nixos/index.html"
  to = "/"
  status = 302
  force = true

[[redirects]]
  from = "/nixos/about.html"
  to = "/explore.html"
  status = 302
  force = true

[[redirects]]
  from = "/nixos/screenshots/*"
  to = "/images/screenshots/:splat"
  status = 302
  force = true

[[redirects]]
  from = "/nixos/klogo-official-crystal-128x128.png"
  to = "/images/klogo-official-crystal-128x128.png"
  status = 302
  force = true

[[redirects]]
  from = "/nixos/download"
  to = "/download"
  status = 302
  force = true

[[redirects]]
  from = "/nixos/foundation.html"
  to = "/community/index.html"
  status = 302
  force = true

[[redirects]]
  from = "/nixos/learn.html"
  to = "/learn.html"
  status = 302
  force = true

[[redirects]]
  from = "/nixos/security.html"
  to = "/community/index.html"
  status = 302
  force = true

[[redirects]]
  from = "/nixos/support.html"
  to = "/community/index.html"
  status = 302
  force = true

[[redirects]]
  from = "/nixos/community.html"
  to = "/community/index.html"
  status = 302
  force = true

[[redirects]]
  from = "/nix-dev"
  to = "https://releases.nixos.org/nix-dev/index.html"
  status = 302
  force = true

[[redirects]]
  from = "/nix-dev/*"
  to = "https://releases.nixos.org/nix-dev/:splat"
  status = 302
  force = true

[[redirects]]
  from = "/tarballs/*"
  to = "https://tarballs.nixos.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/channels/*"
  to = "https://channels.nixos.org/:splat"
  status = 302
  force = true

[[redirects]]
  from = "/releases/channels/*"
  to = "https://channels.nixos.org/:splat"
  status = 302
  force = true

[[redirects]]
  from = "/releases/nixos/channels/*"
  to = "https://channels.nixos.org/nixos/:splat"
  status = 302
  force = true

[[redirects]]
  from = "/releases/nix/:release/install"
  to = "https://releases.nixos.org/nix/:release/install"
  status = 200
  force = true

[[redirects]]
  from = "/releases/*"
  to = "https://releases.nixos.org/:splat"
  status = 302
  force = true

[[redirects]]
  from  = "/nix/install"
  to = "https://channels.nixos.org/nix-latest/install"
  status = 200
  #status = 302
  force = true

[[redirects]]
  from  = "/hydra"
  to = "https://github.com/NixOS/hydra"
  status = 302
  force = true

[[redirects]]
  from  = "/hydra/manual"
  to = "https://hydra.nixos.org/job/hydra/master/manual/latest/download-by-type/doc/manual"
  status = 302
  force = true

[[redirects]]
  from  = "/nixops"
  to = "https://github.com/NixOS/nixops"
  status = 302
  force = true

[[redirects]]
  from  = "/nixops/manual"
  to = "https://hydra.nixos.org/job/nixops/master/tarball/latest/download-by-type/doc/manual"
  status = 302
  force = true

[[redirects]]
  from  = "/disnix"
  to = "https://github.com/svanderburg/disnix"
  status = 302
  force = true

[[redirects]]
  from = "/patchelf.html"
  to = "https://github.com/NixOS/patchelf"
  status = 302
  force = true

[[redirects]]
  from = "/wiki/bootstrap/css/bootstrap.min.css"
  to = "/bootstrap/css/bootstrap.min.css"
  status = 302
  force = true

[[redirects]]
  from = "/wiki/bootstrap/css/bootstrap-responsive.min.css"
  to = "/bootstrap/css/bootstrap-responsive.min.css"
  status = 302
  force = true

[[redirects]]
  from = "/wiki/css/nixos-site.css"
  to = "/css/nixos-site.css"
  status = 302
  force = true

[[redirects]]
  from = "/wiki/bootstrap/js/bootstrap.min.js"
  to = "/bootstrap/js/bootstrap.min.js"
  status = 302
  force = true

[[redirects]]
  from = "/wiki/logo/nix-wiki.png"
  to = "/logo/nix-wiki.png"
  status = 302
  force = true

[[redirects]]
  from = "/wiki/js/jquery-ui.min.js"
  to = "/js/jquery-ui.min.js"
  status = 302
  force = true

[[redirects]]
  from = "/wiki/js/jquery.min.js"
  to = "/js/jquery.min.js"
  status = 302
  force = true

[[redirects]]
  from  = "/~eelco/*"
  to = "https://edolstra.github.io/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/~eelco/pubs/bootstrap/css/bootstrap-responsive.min.css"
  to = "/bootstrap/css/bootstrap-responsive.min.css"
  status = 302
  force = true

[[redirects]]
  from = "/~eelco/pubs/bootstrap/css/bootstrap.min.css"
  to = "/bootstrap/css/bootstrap.min.css"
  status = 302
  force = true

[[redirects]]
  from = "/~eelco/pubs/css/nixos-site.css"
  to = "/css/nixos-site.css"
  status = 302
  force = true

[[redirects]]
  from = "/.well-known/*"
  to = "/well-known/:splat"
  status = 200
  force = true

[[headers]]
  for = "/.well-known/matrix/client"
    [headers.values]
    Access-Control-Allow-Origin = "*"
