[[commercial-provider]]
name = "Black River Software"
url = "http://blackriversoft.com/"
locations = ["Ohio, USA"]
logo = "/community/commercial-support-logos/black-river-software.png"
description = """
Black River Software offers custom software development, software architecture
consulting, and build and deployment engineering services.
"""

[[commercial-provider]]
name = "Determinate Systems"
url = "https://determinate.systems/"
locations = ["Remote", "Massachusetts, USA"]
logo = "/community/commercial-support-logos/determinate-systems.svg"
description = """
Confidently build and deploy to the cloud, stadium, or stock exchange.
Expert help with the Nix ecosystem from Graham Christensen and
collaborators.
"""

[[commercial-provider]]
name = "Enlambda"
url = "https://www.enlambda.com/"
locations = ["Remote", "Estonia"]
logo = "/community/commercial-support-logos/enlambda.png"
description = """
Turning operational issues into development tasks using Nix since 2013.
"""

[[commercial-provider]]
name = "five binaries"
url = "https://www.fivebinaries.com/"
locations = ["Tallinn, Estonia", "Prague, Czech Republic"]
logo = "/community/commercial-support-logos/5inaries.png"
description = """
Five Binaries are an infrastructure development company focused on creating
customized highly reliable solutions for blockchain-powered industries.
"""

[[commercial-provider]]
name = "Helsinki Systems"
url = "https://helsinki-systems.de"
locations = ["Stuttgart, Germany"]
logo = "/community/commercial-support-logos/helsinki-systems.png"
description = """
Your partner for hosting, networks and IT solutions running on NixOS. We have
multiple years of NixOS and decades of Linux experience to aid your NixOS
integration and administration.
"""

[[commercial-provider]]
name = "Mayflower"
url = "https://nixos.mayflower.consulting"
locations = ["Munich, Germany", "Berlin, Germany", "WÃ¼rzburg, Germany"]
logo = "/community/commercial-support-logos/mayflower.png"
description = """
We are Mayflower. We build infrastructure. Declarative &amp; reproducible.
"""

[[commercial-provider]]
name = "Numtide Ltd"
url = "https://www.numtide.com/"
locations = ["London, UK", "Remote"]
logo = "/community/commercial-support-logos/numtide.png"
description = """
Numtide is a Nix and DevOps consulting company. We help our customers with declarative development, cloud and bare-metal infrastructures.
"""

[[commercial-provider]]
name = "Obsidian Systems"
url = "https://obsidian.systems"
locations = ["New York, USA"]
logo = "/community/commercial-support-logos/obsidian-systems.svg"
description = """
Software consultancy specializing in Haskell, Nix, curiosity, and innovation.
"""

[[commercial-provider]]
name = "Platonic.Systems"
url = "https://platonic.systems/"
locations = ["Remote"]
logo = "/community/commercial-support-logos/platonic-systems.svg"
description = """
Solving your toughest software problems
Trying to build an innovative software solution? Is it behind schedule?
Over budget? Not working properly? Growing with bugs? We can help.
"""

[[commercial-provider]]
name = "Serokell"
url = "https://serokell.io/"
locations = ["Remote", "Tallinn, Estonia"]
logo = "/community/commercial-support-logos/serokell.png"
description = """
Serokell is a custom software engineering company that creates innovative
solutions for complex problems. We do software development, consulting, and
auditing.
"""

[[commercial-provider]]
name = "Tweag"
url = "https://tweag.io/"
locations = ["Remote", "Paris, France", "London, UK", "Zurich, Switzerland"]
logo = "/community/commercial-support-logos/tweag.svg"
description = """
We enable deep-tech startups to achieve their vision, from research to product
delivery. Top contributor to Nix and this website.
"""

[[commercial-provider]]
name = "Immutable Solutions"
url = "https://immutablesolutions.com/"
locations = ["Sweden"]
logo = "/community/commercial-support-logos/immutable-solutions.png"
description = """
Nix specialists helping companies design, develop and deploy systems in a
declarative fashion.
"""

[[commercial-provider]]
name = "Nix.How"
url = "https://nix.how"
locations = ["Remote", "United Kingdom"]
logo = "/community/commercial-support-logos/nix-how.png"
description = """
Nix experts specialising in converting legacy infrastructure to a Nix/NixOS
methodology and workflow
"""

[[commercial-provider]]
name = "flox"
url = "https://floxdev.com"
locations = ["Remote", "San Francisco", "London"]
logo = "/community/commercial-support-logos/flox.png"
description = """
flox is a platform for building, sharing, and collaborating across the entire
development lifecycle.
"""

[[commercial-provider]]
name = "core.gen.tr"
url = "https://core.gen.tr"
locations = ["Remote" "Istanbul"]
logo = "/community/commercial-support-logos/core-gen-tr.png"
description = """
We develop and deploy custom cryptographic and post-quantum
cryptographic systems via Nix.
"""